### ISSUE TITLE
Confused?

### ISSUE THREAD

**Issue by iGetUploaded** [CSM-BlueRed/CryptMyRepl#1]
So I'm new to this and tried testing it.. got all the stuff needed I just get confused on the key part. Do I just name the file _**CRYPTIONKEY**_ and then put the key there or what?

**Comment by CSM-BlueRed** [comment]
No, in a Python repl, you have a section nammed **Secrets**, you create a new secret with the name **CRYPTIONKEY** and you put your key as the value.

**Comment by iGetUploaded** [comment]
Ohh okay thanks. Also is the repl supposed to run fine after that or nah? If so Im getting this error 
![image](https://user-images.githubusercontent.com/54633753/189467006-63548326-fa66-4eab-8503-acdb95939c0e.png)

**Comment by CSM-BlueRed** [comment]
your key or the stream is wrong, I think you restarted the program and doesnt update the stream but just the key, try to reset your repl and the key, and restart CryptMyRepl

**Comment by iGetUploaded** [comment]
Got it to work thanks

**Comment by CSM-BlueRed** [comment]
np!
